// tests for userRefresh
// Generated by serverless-mocha-plugin
import { getWrapper } from 'serverless-mocha-plugin';
const wrapped = getWrapper('userRefresh', '/src/lambdas/userRefresh.ts', 'handler');

describe('filed lambda execution', () => {
  it('empty params: not acceptable', async () => {
    const response = await wrapped.run({});
    expect(response.statusCode).toBe(406);
  });

  it('empty body: not acceptable', async () => {
    const response = await wrapped.run({ body: '{}'});
    expect(response.statusCode).toBe(406);
  });

  it('user does not exists: unauthorized', async () => {
    const response = await wrapped.run({ body: JSON.stringify({ refresh: 'invalid'})});
    expect(response.statusCode).toBe(401);
  });
});
